// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A card action. (an ability, an attack or rule text)
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum Action {
    /// A Pokémon ability.
    Ability(crate::cards::action::Ability),

    /// A Pokémon attack.
    Attack(crate::cards::action::Attack),

    /// Plain rule text.
    Text(crate::cards::action::Text),
}
