// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A url-safe identifier with an associated display string.
/// struct Name {
///    
///     // The url-safe identifier. (ex: mega-venusaur)
///     id: string;
///    
///     // The display string. (ex: Mega Venusaur)
///     display: string;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Name {
    id: String,
    display: String,
}

impl Name {
    //! Construction

    /// Creates a new [Name].
    pub const fn new(id: String, display: String) -> Self {
        Self { id, display }
    }

    /// Creates a new [Name].
    pub fn from<F1, F2>(id: F1, display: F2) -> Self
    where
        F1: Into<String>,
        F2: Into<String>,
    {
        Self::new(id.into(), display.into())
    }
}

impl Name {
    //! Field: `id`

    /// Gets the field: `id`.
    #[must_use]
    pub fn id(&self) -> &str {
        self.id.as_str()
    }

    /// Sets the field: `id`. Returns the previous value.
    pub fn set_id(&mut self, id: String) -> String {
        std::mem::replace(&mut self.id, id)
    }

    /// Sets the field: `id`. Returns the struct itself.
    #[must_use]
    pub fn with_id(mut self, id: String) -> Self {
        self.set_id(id);
        self
    }
}

impl Name {
    //! Field: `display`

    /// Gets the field: `display`.
    #[must_use]
    pub fn display(&self) -> &str {
        self.display.as_str()
    }

    /// Sets the field: `display`. Returns the previous value.
    pub fn set_display(&mut self, display: String) -> String {
        std::mem::replace(&mut self.display, display)
    }

    /// Sets the field: `display`. Returns the struct itself.
    #[must_use]
    pub fn with_display(mut self, display: String) -> Self {
        self.set_display(display);
        self
    }
}
