// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A Pokémon ability.
/// message Ability {
///    
///     // The ability kind. (ex: `Ability`, `Poké-Power`, `Poké-Body`)
///     kind: core.web.Name = 1;
///    
///     // The ability name.
///     name: core.web.Name = 2;
///    
///     // The ability text.
///     text: string = 3;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Ability {
    #[serde(skip_serializing_if = "Option::is_none")]
    kind: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    text: Option<String>,
}

impl Ability {
    //! Field: `kind`

    /// Gets the field: `kind`.
    #[must_use]
    pub fn kind(&self) -> Option<&crate::core::web::Name> {
        self.kind.as_ref()
    }

    /// Sets the field: `kind`. Returns the previous value.
    pub fn set_kind<F>(&mut self, kind: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let kind: Option<crate::core::web::Name> = kind.into();
        std::mem::replace(&mut self.kind, kind)
    }

    /// Sets the field: `kind`. Returns the struct itself.
    #[must_use]
    pub fn with_kind<F>(mut self, kind: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_kind(kind);
        self
    }
}

impl Ability {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> Option<&crate::core::web::Name> {
        self.name.as_ref()
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name<F>(&mut self, name: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let name: Option<crate::core::web::Name> = name.into();
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name<F>(mut self, name: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_name(name);
        self
    }
}

impl Ability {
    //! Field: `text`

    /// Gets the field: `text`.
    #[must_use]
    pub fn text(&self) -> Option<&str> {
        self.text.as_deref()
    }

    /// Sets the field: `text`. Returns the previous value.
    pub fn set_text<F>(&mut self, text: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let text: Option<String> = text.into();
        std::mem::replace(&mut self.text, text)
    }

    /// Sets the field: `text`. Returns the struct itself.
    #[must_use]
    pub fn with_text<F>(mut self, text: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_text(text);
        self
    }
}
