// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// An Energy card.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum EnergyCard {
    /// A basic energy. (ex: `Psychic Energy`)
    Basic(crate::cards::meta::EnergyType),

    /// A special energy. (ex: `Double Colorless Energy`)
    Special(crate::cards::energy::SpecialEnergy),
}
