// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A weakness or resistance type modifier.
/// message TypeModifier {
///    
///     // The energy types.
///     energy_types: []cards.meta.EnergyType = 1;
///    
///     // The scalar. (ex: `2` in `×2`, `30` in `−30`)
///     scalar: u32 = 2;
///    
///     // The modifier. (ex: `×` in `×2`)
///     modifier: cards.meta.DamageModifier = 3;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct TypeModifier {
    #[serde(skip_serializing_if = "Option::is_none")]
    energy_types: Option<Vec<crate::cards::meta::EnergyType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    scalar: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    modifier: Option<crate::cards::meta::DamageModifier>,
}

impl TypeModifier {
    //! Field: `energy_types`

    /// Gets the field: `energy_types`.
    #[must_use]
    pub fn energy_types(&self) -> Option<&Vec<crate::cards::meta::EnergyType>> {
        self.energy_types.as_ref()
    }

    /// Sets the field: `energy_types`. Returns the previous value.
    pub fn set_energy_types<F>(
        &mut self,
        energy_types: F,
    ) -> Option<Vec<crate::cards::meta::EnergyType>>
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        let energy_types: Option<Vec<crate::cards::meta::EnergyType>> = energy_types.into();
        std::mem::replace(&mut self.energy_types, energy_types)
    }

    /// Sets the field: `energy_types`. Returns the struct itself.
    #[must_use]
    pub fn with_energy_types<F>(mut self, energy_types: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        self.set_energy_types(energy_types);
        self
    }
}

impl TypeModifier {
    //! Field: `scalar`

    /// Gets the field: `scalar`.
    #[must_use]
    pub fn scalar(&self) -> Option<u32> {
        self.scalar
    }

    /// Sets the field: `scalar`. Returns the previous value.
    pub fn set_scalar<F>(&mut self, scalar: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let scalar: Option<u32> = scalar.into();
        std::mem::replace(&mut self.scalar, scalar)
    }

    /// Sets the field: `scalar`. Returns the struct itself.
    #[must_use]
    pub fn with_scalar<F>(mut self, scalar: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_scalar(scalar);
        self
    }
}

impl TypeModifier {
    //! Field: `modifier`

    /// Gets the field: `modifier`.
    #[must_use]
    pub fn modifier(&self) -> Option<crate::cards::meta::DamageModifier> {
        self.modifier
    }

    /// Sets the field: `modifier`. Returns the previous value.
    pub fn set_modifier<F>(&mut self, modifier: F) -> Option<crate::cards::meta::DamageModifier>
    where
        F: Into<Option<crate::cards::meta::DamageModifier>>,
    {
        let modifier: Option<crate::cards::meta::DamageModifier> = modifier.into();
        std::mem::replace(&mut self.modifier, modifier)
    }

    /// Sets the field: `modifier`. Returns the struct itself.
    #[must_use]
    pub fn with_modifier<F>(mut self, modifier: F) -> Self
    where
        F: Into<Option<crate::cards::meta::DamageModifier>>,
    {
        self.set_modifier(modifier);
        self
    }
}
