// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A card set.
/// struct CardSet {
///    
///     // The set name. (ex: Base Set)
///     name: core.web.Name;
///    
///     // The series name. (ex: Classic)
///     series: core.web.Name;
///    
///     // The card context. (ex: English)
///     context: cards.set.CardContext;
///    
///     // The pokemon TCG live code. (ex: BS)
///     live_code: optional core.web.Name;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct CardSet {
    name: crate::core::web::Name,
    series: crate::core::web::Name,
    context: crate::cards::set::CardContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    live_code: Option<crate::core::web::Name>,
}

impl CardSet {
    //! Construction

    /// Creates a new [CardSet].
    pub const fn new(
        name: crate::core::web::Name,
        series: crate::core::web::Name,
        context: crate::cards::set::CardContext,
        live_code: Option<crate::core::web::Name>,
    ) -> Self {
        Self {
            name,
            series,
            context,
            live_code,
        }
    }

    /// Creates a new [CardSet].
    pub fn from<F1, F2, F3, F4>(name: F1, series: F2, context: F3, live_code: F4) -> Self
    where
        F1: Into<crate::core::web::Name>,
        F2: Into<crate::core::web::Name>,
        F3: Into<crate::cards::set::CardContext>,
        F4: Into<Option<crate::core::web::Name>>,
    {
        Self::new(name.into(), series.into(), context.into(), live_code.into())
    }
}

impl CardSet {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> &crate::core::web::Name {
        &self.name
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name(&mut self, name: crate::core::web::Name) -> crate::core::web::Name {
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name(mut self, name: crate::core::web::Name) -> Self {
        self.set_name(name);
        self
    }
}

impl CardSet {
    //! Field: `series`

    /// Gets the field: `series`.
    #[must_use]
    pub fn series(&self) -> &crate::core::web::Name {
        &self.series
    }

    /// Sets the field: `series`. Returns the previous value.
    pub fn set_series(&mut self, series: crate::core::web::Name) -> crate::core::web::Name {
        std::mem::replace(&mut self.series, series)
    }

    /// Sets the field: `series`. Returns the struct itself.
    #[must_use]
    pub fn with_series(mut self, series: crate::core::web::Name) -> Self {
        self.set_series(series);
        self
    }
}

impl CardSet {
    //! Field: `context`

    /// Gets the field: `context`.
    #[must_use]
    pub fn context(&self) -> crate::cards::set::CardContext {
        self.context
    }

    /// Sets the field: `context`. Returns the previous value.
    pub fn set_context(
        &mut self,
        context: crate::cards::set::CardContext,
    ) -> crate::cards::set::CardContext {
        std::mem::replace(&mut self.context, context)
    }

    /// Sets the field: `context`. Returns the struct itself.
    #[must_use]
    pub fn with_context(mut self, context: crate::cards::set::CardContext) -> Self {
        self.set_context(context);
        self
    }
}

impl CardSet {
    //! Field: `live_code`

    /// Gets the field: `live_code`.
    #[must_use]
    pub fn live_code(&self) -> Option<&crate::core::web::Name> {
        self.live_code.as_ref()
    }

    /// Sets the field: `live_code`. Returns the previous value.
    pub fn set_live_code<F>(&mut self, live_code: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let live_code: Option<crate::core::web::Name> = live_code.into();
        std::mem::replace(&mut self.live_code, live_code)
    }

    /// Sets the field: `live_code`. Returns the struct itself.
    #[must_use]
    pub fn with_live_code<F>(mut self, live_code: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_live_code(live_code);
        self
    }
}
