// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A Trainer card.
/// message TrainerCard {
///    
///     // The hit points. (ex: fossil trainer cards)
///     hit_points: u32 = 1;
///    
///     // The card text.
///     text: string = 2;
///    
///     // The actions. (ex: fossil abilities & technical machine attacks)
///     actions: []cards.action.Action = 3;
///    
///     // The trainer type.
///     sub: cards.trainer.TrainerType = 4;
///    
///     // Secondary sub-types. (ex: `Ace Spec`, `Technical Machine`)
///     secondary_subs: []core.web.Name = 5;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct TrainerCard {
    #[serde(skip_serializing_if = "Option::is_none")]
    hit_points: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    actions: Option<Vec<crate::cards::action::Action>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    sub: Option<crate::cards::trainer::TrainerType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    secondary_subs: Option<Vec<crate::core::web::Name>>,
}

impl TrainerCard {
    //! Field: `hit_points`

    /// Gets the field: `hit_points`.
    #[must_use]
    pub fn hit_points(&self) -> Option<u32> {
        self.hit_points
    }

    /// Sets the field: `hit_points`. Returns the previous value.
    pub fn set_hit_points<F>(&mut self, hit_points: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let hit_points: Option<u32> = hit_points.into();
        std::mem::replace(&mut self.hit_points, hit_points)
    }

    /// Sets the field: `hit_points`. Returns the struct itself.
    #[must_use]
    pub fn with_hit_points<F>(mut self, hit_points: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_hit_points(hit_points);
        self
    }
}

impl TrainerCard {
    //! Field: `text`

    /// Gets the field: `text`.
    #[must_use]
    pub fn text(&self) -> Option<&str> {
        self.text.as_deref()
    }

    /// Sets the field: `text`. Returns the previous value.
    pub fn set_text<F>(&mut self, text: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let text: Option<String> = text.into();
        std::mem::replace(&mut self.text, text)
    }

    /// Sets the field: `text`. Returns the struct itself.
    #[must_use]
    pub fn with_text<F>(mut self, text: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_text(text);
        self
    }
}

impl TrainerCard {
    //! Field: `actions`

    /// Gets the field: `actions`.
    #[must_use]
    pub fn actions(&self) -> Option<&Vec<crate::cards::action::Action>> {
        self.actions.as_ref()
    }

    /// Sets the field: `actions`. Returns the previous value.
    pub fn set_actions<F>(&mut self, actions: F) -> Option<Vec<crate::cards::action::Action>>
    where
        F: Into<Option<Vec<crate::cards::action::Action>>>,
    {
        let actions: Option<Vec<crate::cards::action::Action>> = actions.into();
        std::mem::replace(&mut self.actions, actions)
    }

    /// Sets the field: `actions`. Returns the struct itself.
    #[must_use]
    pub fn with_actions<F>(mut self, actions: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::action::Action>>>,
    {
        self.set_actions(actions);
        self
    }
}

impl TrainerCard {
    //! Field: `sub`

    /// Gets the field: `sub`.
    #[must_use]
    pub fn sub(&self) -> Option<crate::cards::trainer::TrainerType> {
        self.sub
    }

    /// Sets the field: `sub`. Returns the previous value.
    pub fn set_sub<F>(&mut self, sub: F) -> Option<crate::cards::trainer::TrainerType>
    where
        F: Into<Option<crate::cards::trainer::TrainerType>>,
    {
        let sub: Option<crate::cards::trainer::TrainerType> = sub.into();
        std::mem::replace(&mut self.sub, sub)
    }

    /// Sets the field: `sub`. Returns the struct itself.
    #[must_use]
    pub fn with_sub<F>(mut self, sub: F) -> Self
    where
        F: Into<Option<crate::cards::trainer::TrainerType>>,
    {
        self.set_sub(sub);
        self
    }
}

impl TrainerCard {
    //! Field: `secondary_subs`

    /// Gets the field: `secondary_subs`.
    #[must_use]
    pub fn secondary_subs(&self) -> Option<&Vec<crate::core::web::Name>> {
        self.secondary_subs.as_ref()
    }

    /// Sets the field: `secondary_subs`. Returns the previous value.
    pub fn set_secondary_subs<F>(
        &mut self,
        secondary_subs: F,
    ) -> Option<Vec<crate::core::web::Name>>
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        let secondary_subs: Option<Vec<crate::core::web::Name>> = secondary_subs.into();
        std::mem::replace(&mut self.secondary_subs, secondary_subs)
    }

    /// Sets the field: `secondary_subs`. Returns the struct itself.
    #[must_use]
    pub fn with_secondary_subs<F>(mut self, secondary_subs: F) -> Self
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        self.set_secondary_subs(secondary_subs);
        self
    }
}
