// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A card sub-type.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum CardType {
    /// A Pokémon card.
    Pokemon(crate::cards::pokemon::PokemonCard),

    /// A Trainer card.
    Trainer(crate::cards::trainer::TrainerCard),

    /// An Energy card.
    Energy(crate::cards::energy::EnergyCard),
}
