// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_card` request.
/// message GetCardRequest {
///    
///     // The card id. (ex: alakazam-base-set-1)
///     id: string = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetCardRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    id: Option<String>,
}

impl GetCardRequest {
    //! Field: `id`

    /// Gets the field: `id`.
    #[must_use]
    pub fn id(&self) -> Option<&str> {
        self.id.as_deref()
    }

    /// Sets the field: `id`. Returns the previous value.
    pub fn set_id<F>(&mut self, id: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let id: Option<String> = id.into();
        std::mem::replace(&mut self.id, id)
    }

    /// Sets the field: `id`. Returns the struct itself.
    #[must_use]
    pub fn with_id<F>(mut self, id: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_id(id);
        self
    }
}
