// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A Pokémon attack.
/// message Attack {
///    
///     // The attack name.
///     name: core.web.Name = 1;
///    
///     // The energy cost.
///     cost: []cards.meta.EnergyType = 2;
///    
///     // The damage.
///     damage: cards.action.Damage = 3;
///    
///     // The attack text.
///     text: string = 4;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Attack {
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    cost: Option<Vec<crate::cards::meta::EnergyType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    damage: Option<crate::cards::action::Damage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    text: Option<String>,
}

impl Attack {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> Option<&crate::core::web::Name> {
        self.name.as_ref()
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name<F>(&mut self, name: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let name: Option<crate::core::web::Name> = name.into();
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name<F>(mut self, name: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_name(name);
        self
    }
}

impl Attack {
    //! Field: `cost`

    /// Gets the field: `cost`.
    #[must_use]
    pub fn cost(&self) -> Option<&Vec<crate::cards::meta::EnergyType>> {
        self.cost.as_ref()
    }

    /// Sets the field: `cost`. Returns the previous value.
    pub fn set_cost<F>(&mut self, cost: F) -> Option<Vec<crate::cards::meta::EnergyType>>
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        let cost: Option<Vec<crate::cards::meta::EnergyType>> = cost.into();
        std::mem::replace(&mut self.cost, cost)
    }

    /// Sets the field: `cost`. Returns the struct itself.
    #[must_use]
    pub fn with_cost<F>(mut self, cost: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        self.set_cost(cost);
        self
    }
}

impl Attack {
    //! Field: `damage`

    /// Gets the field: `damage`.
    #[must_use]
    pub fn damage(&self) -> Option<&crate::cards::action::Damage> {
        self.damage.as_ref()
    }

    /// Sets the field: `damage`. Returns the previous value.
    pub fn set_damage<F>(&mut self, damage: F) -> Option<crate::cards::action::Damage>
    where
        F: Into<Option<crate::cards::action::Damage>>,
    {
        let damage: Option<crate::cards::action::Damage> = damage.into();
        std::mem::replace(&mut self.damage, damage)
    }

    /// Sets the field: `damage`. Returns the struct itself.
    #[must_use]
    pub fn with_damage<F>(mut self, damage: F) -> Self
    where
        F: Into<Option<crate::cards::action::Damage>>,
    {
        self.set_damage(damage);
        self
    }
}

impl Attack {
    //! Field: `text`

    /// Gets the field: `text`.
    #[must_use]
    pub fn text(&self) -> Option<&str> {
        self.text.as_deref()
    }

    /// Sets the field: `text`. Returns the previous value.
    pub fn set_text<F>(&mut self, text: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let text: Option<String> = text.into();
        std::mem::replace(&mut self.text, text)
    }

    /// Sets the field: `text`. Returns the struct itself.
    #[must_use]
    pub fn with_text<F>(mut self, text: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_text(text);
        self
    }
}
