// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A damage modifier symbol. (ex: `+` in `30+`, `×` in `30×` / `×2`)
#[derive(
    Copy,
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub enum DamageModifier {
    Plus,

    Times,

    Minus,
}
