// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_sets` response.
/// message GetSetsResponse {
///    
///     // The sets.
///     sets: []cards.set.CardSet = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetSetsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    sets: Option<Vec<crate::cards::set::CardSet>>,
}

impl GetSetsResponse {
    //! Field: `sets`

    /// Gets the field: `sets`.
    #[must_use]
    pub fn sets(&self) -> Option<&Vec<crate::cards::set::CardSet>> {
        self.sets.as_ref()
    }

    /// Sets the field: `sets`. Returns the previous value.
    pub fn set_sets<F>(&mut self, sets: F) -> Option<Vec<crate::cards::set::CardSet>>
    where
        F: Into<Option<Vec<crate::cards::set::CardSet>>>,
    {
        let sets: Option<Vec<crate::cards::set::CardSet>> = sets.into();
        std::mem::replace(&mut self.sets, sets)
    }

    /// Sets the field: `sets`. Returns the struct itself.
    #[must_use]
    pub fn with_sets<F>(mut self, sets: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::set::CardSet>>>,
    {
        self.set_sets(sets);
        self
    }
}
