// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // Plain rule text. (ex: card rules & reminders)
/// message Text {
///    
///     // The text.
///     text: string = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Text {
    #[serde(skip_serializing_if = "Option::is_none")]
    text: Option<String>,
}

impl Text {
    //! Field: `text`

    /// Gets the field: `text`.
    #[must_use]
    pub fn text(&self) -> Option<&str> {
        self.text.as_deref()
    }

    /// Sets the field: `text`. Returns the previous value.
    pub fn set_text<F>(&mut self, text: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let text: Option<String> = text.into();
        std::mem::replace(&mut self.text, text)
    }

    /// Sets the field: `text`. Returns the struct itself.
    #[must_use]
    pub fn with_text<F>(mut self, text: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_text(text);
        self
    }
}
