// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A single card.
/// struct Card {
///    
///     // The card title. (its name, ex: `Eevee`)
///     title: core.web.Name;
///    
///     // The card style/variant. (DERIVED — left blank by the scrape)
///     style: optional core.web.Name;
///    
///     // The card number.
///     number: cards.card.CardNumber;
///    
///     // The card metadata.
///     meta: cards.meta.CardMeta;
///    
///     // The card sub-type. (Pokémon, Trainer or Energy)
///     sub: cards.card.CardType;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Card {
    title: crate::core::web::Name,
    #[serde(skip_serializing_if = "Option::is_none")]
    style: Option<crate::core::web::Name>,
    number: crate::cards::card::CardNumber,
    meta: crate::cards::meta::CardMeta,
    sub: crate::cards::card::CardType,
}

impl Card {
    //! Construction

    /// Creates a new [Card].
    pub const fn new(
        title: crate::core::web::Name,
        style: Option<crate::core::web::Name>,
        number: crate::cards::card::CardNumber,
        meta: crate::cards::meta::CardMeta,
        sub: crate::cards::card::CardType,
    ) -> Self {
        Self {
            title,
            style,
            number,
            meta,
            sub,
        }
    }

    /// Creates a new [Card].
    pub fn from<F1, F2, F3, F4, F5>(title: F1, style: F2, number: F3, meta: F4, sub: F5) -> Self
    where
        F1: Into<crate::core::web::Name>,
        F2: Into<Option<crate::core::web::Name>>,
        F3: Into<crate::cards::card::CardNumber>,
        F4: Into<crate::cards::meta::CardMeta>,
        F5: Into<crate::cards::card::CardType>,
    {
        Self::new(
            title.into(),
            style.into(),
            number.into(),
            meta.into(),
            sub.into(),
        )
    }
}

impl Card {
    //! Field: `title`

    /// Gets the field: `title`.
    #[must_use]
    pub fn title(&self) -> &crate::core::web::Name {
        &self.title
    }

    /// Sets the field: `title`. Returns the previous value.
    pub fn set_title(&mut self, title: crate::core::web::Name) -> crate::core::web::Name {
        std::mem::replace(&mut self.title, title)
    }

    /// Sets the field: `title`. Returns the struct itself.
    #[must_use]
    pub fn with_title(mut self, title: crate::core::web::Name) -> Self {
        self.set_title(title);
        self
    }
}

impl Card {
    //! Field: `style`

    /// Gets the field: `style`.
    #[must_use]
    pub fn style(&self) -> Option<&crate::core::web::Name> {
        self.style.as_ref()
    }

    /// Sets the field: `style`. Returns the previous value.
    pub fn set_style<F>(&mut self, style: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let style: Option<crate::core::web::Name> = style.into();
        std::mem::replace(&mut self.style, style)
    }

    /// Sets the field: `style`. Returns the struct itself.
    #[must_use]
    pub fn with_style<F>(mut self, style: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_style(style);
        self
    }
}

impl Card {
    //! Field: `number`

    /// Gets the field: `number`.
    #[must_use]
    pub fn number(&self) -> &crate::cards::card::CardNumber {
        &self.number
    }

    /// Sets the field: `number`. Returns the previous value.
    pub fn set_number(
        &mut self,
        number: crate::cards::card::CardNumber,
    ) -> crate::cards::card::CardNumber {
        std::mem::replace(&mut self.number, number)
    }

    /// Sets the field: `number`. Returns the struct itself.
    #[must_use]
    pub fn with_number(mut self, number: crate::cards::card::CardNumber) -> Self {
        self.set_number(number);
        self
    }
}

impl Card {
    //! Field: `meta`

    /// Gets the field: `meta`.
    #[must_use]
    pub fn meta(&self) -> &crate::cards::meta::CardMeta {
        &self.meta
    }

    /// Sets the field: `meta`. Returns the previous value.
    pub fn set_meta(&mut self, meta: crate::cards::meta::CardMeta) -> crate::cards::meta::CardMeta {
        std::mem::replace(&mut self.meta, meta)
    }

    /// Sets the field: `meta`. Returns the struct itself.
    #[must_use]
    pub fn with_meta(mut self, meta: crate::cards::meta::CardMeta) -> Self {
        self.set_meta(meta);
        self
    }
}

impl Card {
    //! Field: `sub`

    /// Gets the field: `sub`.
    #[must_use]
    pub fn sub(&self) -> &crate::cards::card::CardType {
        &self.sub
    }

    /// Sets the field: `sub`. Returns the previous value.
    pub fn set_sub(&mut self, sub: crate::cards::card::CardType) -> crate::cards::card::CardType {
        std::mem::replace(&mut self.sub, sub)
    }

    /// Sets the field: `sub`. Returns the struct itself.
    #[must_use]
    pub fn with_sub(mut self, sub: crate::cards::card::CardType) -> Self {
        self.set_sub(sub);
        self
    }
}
