// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A `get_cards` query.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum CardQuery {
    /// The set id. (ex: base-set)
    SetId(String),

    /// A search query. (query language, ex: `pokemon:charizard Flame`)
    Search(String),
}
