// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A card number. (ex: `RC14` of `RC32`)
/// message CardNumber {
///    
///     // The number. (ex: `RC14`)
///     number: core.web.Name = 1;
///    
///     // The printed total. (ex: `RC32`)
///     printed_total: string = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct CardNumber {
    #[serde(skip_serializing_if = "Option::is_none")]
    number: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    printed_total: Option<String>,
}

impl CardNumber {
    //! Field: `number`

    /// Gets the field: `number`.
    #[must_use]
    pub fn number(&self) -> Option<&crate::core::web::Name> {
        self.number.as_ref()
    }

    /// Sets the field: `number`. Returns the previous value.
    pub fn set_number<F>(&mut self, number: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let number: Option<crate::core::web::Name> = number.into();
        std::mem::replace(&mut self.number, number)
    }

    /// Sets the field: `number`. Returns the struct itself.
    #[must_use]
    pub fn with_number<F>(mut self, number: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_number(number);
        self
    }
}

impl CardNumber {
    //! Field: `printed_total`

    /// Gets the field: `printed_total`.
    #[must_use]
    pub fn printed_total(&self) -> Option<&str> {
        self.printed_total.as_deref()
    }

    /// Sets the field: `printed_total`. Returns the previous value.
    pub fn set_printed_total<F>(&mut self, printed_total: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let printed_total: Option<String> = printed_total.into();
        std::mem::replace(&mut self.printed_total, printed_total)
    }

    /// Sets the field: `printed_total`. Returns the struct itself.
    #[must_use]
    pub fn with_printed_total<F>(mut self, printed_total: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_printed_total(printed_total);
        self
    }
}
