// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A Pokémon card evolution. (stage & evolves-from)
/// message Evolution {
///    
///     // The stage. (ex: `Stage 1`)
///     stage: core.web.Name = 1;
///    
///     // The Pokémon this evolves from.
///     evolves_from: []core.web.Name = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Evolution {
    #[serde(skip_serializing_if = "Option::is_none")]
    stage: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    evolves_from: Option<Vec<crate::core::web::Name>>,
}

impl Evolution {
    //! Field: `stage`

    /// Gets the field: `stage`.
    #[must_use]
    pub fn stage(&self) -> Option<&crate::core::web::Name> {
        self.stage.as_ref()
    }

    /// Sets the field: `stage`. Returns the previous value.
    pub fn set_stage<F>(&mut self, stage: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let stage: Option<crate::core::web::Name> = stage.into();
        std::mem::replace(&mut self.stage, stage)
    }

    /// Sets the field: `stage`. Returns the struct itself.
    #[must_use]
    pub fn with_stage<F>(mut self, stage: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_stage(stage);
        self
    }
}

impl Evolution {
    //! Field: `evolves_from`

    /// Gets the field: `evolves_from`.
    #[must_use]
    pub fn evolves_from(&self) -> Option<&Vec<crate::core::web::Name>> {
        self.evolves_from.as_ref()
    }

    /// Sets the field: `evolves_from`. Returns the previous value.
    pub fn set_evolves_from<F>(&mut self, evolves_from: F) -> Option<Vec<crate::core::web::Name>>
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        let evolves_from: Option<Vec<crate::core::web::Name>> = evolves_from.into();
        std::mem::replace(&mut self.evolves_from, evolves_from)
    }

    /// Sets the field: `evolves_from`. Returns the struct itself.
    #[must_use]
    pub fn with_evolves_from<F>(mut self, evolves_from: F) -> Self
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        self.set_evolves_from(evolves_from);
        self
    }
}
