// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_sets` request.
/// message GetSetsRequest {
///    
///     // The card context. (optional)
///     context: cards.set.CardContext = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetSetsRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    context: Option<crate::cards::set::CardContext>,
}

impl GetSetsRequest {
    //! Field: `context`

    /// Gets the field: `context`.
    #[must_use]
    pub fn context(&self) -> Option<crate::cards::set::CardContext> {
        self.context
    }

    /// Sets the field: `context`. Returns the previous value.
    pub fn set_context<F>(&mut self, context: F) -> Option<crate::cards::set::CardContext>
    where
        F: Into<Option<crate::cards::set::CardContext>>,
    {
        let context: Option<crate::cards::set::CardContext> = context.into();
        std::mem::replace(&mut self.context, context)
    }

    /// Sets the field: `context`. Returns the struct itself.
    #[must_use]
    pub fn with_context<F>(mut self, context: F) -> Self
    where
        F: Into<Option<crate::cards::set::CardContext>>,
    {
        self.set_context(context);
        self
    }
}
