// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_card` response.
/// message GetCardResponse {
///    
///     // The card.
///     card: cards.card.Card = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetCardResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    card: Option<crate::cards::card::Card>,
}

impl GetCardResponse {
    //! Field: `card`

    /// Gets the field: `card`.
    #[must_use]
    pub fn card(&self) -> Option<&crate::cards::card::Card> {
        self.card.as_ref()
    }

    /// Sets the field: `card`. Returns the previous value.
    pub fn set_card<F>(&mut self, card: F) -> Option<crate::cards::card::Card>
    where
        F: Into<Option<crate::cards::card::Card>>,
    {
        let card: Option<crate::cards::card::Card> = card.into();
        std::mem::replace(&mut self.card, card)
    }

    /// Sets the field: `card`. Returns the struct itself.
    #[must_use]
    pub fn with_card<F>(mut self, card: F) -> Self
    where
        F: Into<Option<crate::cards::card::Card>>,
    {
        self.set_card(card);
        self
    }
}
