// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A Pokémon card.
/// message PokemonCard {
///    
///     // The Pokémon. (empty for fossils, ex: `Buried Fossil`)
///     pokemon: []pokemon.Pokemon = 1;
///    
///     // The hit points.
///     hit_points: u32 = 2;
///    
///     // The Pokémon types.
///     energy_types: []cards.meta.EnergyType = 3;
///    
///     // The evolution. (stage & evolves-from)
///     evolution: cards.pokemon.Evolution = 4;
///    
///     // The abilities & attacks.
///     actions: []cards.action.Action = 5;
///    
///     // The retreat cost.
///     retreat_cost: u32 = 6;
///    
///     // The weaknesses.
///     weaknesses: []cards.pokemon.TypeModifier = 7;
///    
///     // The resistances.
///     resistances: []cards.pokemon.TypeModifier = 8;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct PokemonCard {
    #[serde(skip_serializing_if = "Option::is_none")]
    pokemon: Option<Vec<crate::pokemon::Pokemon>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    hit_points: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    energy_types: Option<Vec<crate::cards::meta::EnergyType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    evolution: Option<crate::cards::pokemon::Evolution>,
    #[serde(skip_serializing_if = "Option::is_none")]
    actions: Option<Vec<crate::cards::action::Action>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    retreat_cost: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    weaknesses: Option<Vec<crate::cards::pokemon::TypeModifier>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    resistances: Option<Vec<crate::cards::pokemon::TypeModifier>>,
}

impl PokemonCard {
    //! Field: `pokemon`

    /// Gets the field: `pokemon`.
    #[must_use]
    pub fn pokemon(&self) -> Option<&Vec<crate::pokemon::Pokemon>> {
        self.pokemon.as_ref()
    }

    /// Sets the field: `pokemon`. Returns the previous value.
    pub fn set_pokemon<F>(&mut self, pokemon: F) -> Option<Vec<crate::pokemon::Pokemon>>
    where
        F: Into<Option<Vec<crate::pokemon::Pokemon>>>,
    {
        let pokemon: Option<Vec<crate::pokemon::Pokemon>> = pokemon.into();
        std::mem::replace(&mut self.pokemon, pokemon)
    }

    /// Sets the field: `pokemon`. Returns the struct itself.
    #[must_use]
    pub fn with_pokemon<F>(mut self, pokemon: F) -> Self
    where
        F: Into<Option<Vec<crate::pokemon::Pokemon>>>,
    {
        self.set_pokemon(pokemon);
        self
    }
}

impl PokemonCard {
    //! Field: `hit_points`

    /// Gets the field: `hit_points`.
    #[must_use]
    pub fn hit_points(&self) -> Option<u32> {
        self.hit_points
    }

    /// Sets the field: `hit_points`. Returns the previous value.
    pub fn set_hit_points<F>(&mut self, hit_points: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let hit_points: Option<u32> = hit_points.into();
        std::mem::replace(&mut self.hit_points, hit_points)
    }

    /// Sets the field: `hit_points`. Returns the struct itself.
    #[must_use]
    pub fn with_hit_points<F>(mut self, hit_points: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_hit_points(hit_points);
        self
    }
}

impl PokemonCard {
    //! Field: `energy_types`

    /// Gets the field: `energy_types`.
    #[must_use]
    pub fn energy_types(&self) -> Option<&Vec<crate::cards::meta::EnergyType>> {
        self.energy_types.as_ref()
    }

    /// Sets the field: `energy_types`. Returns the previous value.
    pub fn set_energy_types<F>(
        &mut self,
        energy_types: F,
    ) -> Option<Vec<crate::cards::meta::EnergyType>>
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        let energy_types: Option<Vec<crate::cards::meta::EnergyType>> = energy_types.into();
        std::mem::replace(&mut self.energy_types, energy_types)
    }

    /// Sets the field: `energy_types`. Returns the struct itself.
    #[must_use]
    pub fn with_energy_types<F>(mut self, energy_types: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::meta::EnergyType>>>,
    {
        self.set_energy_types(energy_types);
        self
    }
}

impl PokemonCard {
    //! Field: `evolution`

    /// Gets the field: `evolution`.
    #[must_use]
    pub fn evolution(&self) -> Option<&crate::cards::pokemon::Evolution> {
        self.evolution.as_ref()
    }

    /// Sets the field: `evolution`. Returns the previous value.
    pub fn set_evolution<F>(&mut self, evolution: F) -> Option<crate::cards::pokemon::Evolution>
    where
        F: Into<Option<crate::cards::pokemon::Evolution>>,
    {
        let evolution: Option<crate::cards::pokemon::Evolution> = evolution.into();
        std::mem::replace(&mut self.evolution, evolution)
    }

    /// Sets the field: `evolution`. Returns the struct itself.
    #[must_use]
    pub fn with_evolution<F>(mut self, evolution: F) -> Self
    where
        F: Into<Option<crate::cards::pokemon::Evolution>>,
    {
        self.set_evolution(evolution);
        self
    }
}

impl PokemonCard {
    //! Field: `actions`

    /// Gets the field: `actions`.
    #[must_use]
    pub fn actions(&self) -> Option<&Vec<crate::cards::action::Action>> {
        self.actions.as_ref()
    }

    /// Sets the field: `actions`. Returns the previous value.
    pub fn set_actions<F>(&mut self, actions: F) -> Option<Vec<crate::cards::action::Action>>
    where
        F: Into<Option<Vec<crate::cards::action::Action>>>,
    {
        let actions: Option<Vec<crate::cards::action::Action>> = actions.into();
        std::mem::replace(&mut self.actions, actions)
    }

    /// Sets the field: `actions`. Returns the struct itself.
    #[must_use]
    pub fn with_actions<F>(mut self, actions: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::action::Action>>>,
    {
        self.set_actions(actions);
        self
    }
}

impl PokemonCard {
    //! Field: `retreat_cost`

    /// Gets the field: `retreat_cost`.
    #[must_use]
    pub fn retreat_cost(&self) -> Option<u32> {
        self.retreat_cost
    }

    /// Sets the field: `retreat_cost`. Returns the previous value.
    pub fn set_retreat_cost<F>(&mut self, retreat_cost: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let retreat_cost: Option<u32> = retreat_cost.into();
        std::mem::replace(&mut self.retreat_cost, retreat_cost)
    }

    /// Sets the field: `retreat_cost`. Returns the struct itself.
    #[must_use]
    pub fn with_retreat_cost<F>(mut self, retreat_cost: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_retreat_cost(retreat_cost);
        self
    }
}

impl PokemonCard {
    //! Field: `weaknesses`

    /// Gets the field: `weaknesses`.
    #[must_use]
    pub fn weaknesses(&self) -> Option<&Vec<crate::cards::pokemon::TypeModifier>> {
        self.weaknesses.as_ref()
    }

    /// Sets the field: `weaknesses`. Returns the previous value.
    pub fn set_weaknesses<F>(
        &mut self,
        weaknesses: F,
    ) -> Option<Vec<crate::cards::pokemon::TypeModifier>>
    where
        F: Into<Option<Vec<crate::cards::pokemon::TypeModifier>>>,
    {
        let weaknesses: Option<Vec<crate::cards::pokemon::TypeModifier>> = weaknesses.into();
        std::mem::replace(&mut self.weaknesses, weaknesses)
    }

    /// Sets the field: `weaknesses`. Returns the struct itself.
    #[must_use]
    pub fn with_weaknesses<F>(mut self, weaknesses: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::pokemon::TypeModifier>>>,
    {
        self.set_weaknesses(weaknesses);
        self
    }
}

impl PokemonCard {
    //! Field: `resistances`

    /// Gets the field: `resistances`.
    #[must_use]
    pub fn resistances(&self) -> Option<&Vec<crate::cards::pokemon::TypeModifier>> {
        self.resistances.as_ref()
    }

    /// Sets the field: `resistances`. Returns the previous value.
    pub fn set_resistances<F>(
        &mut self,
        resistances: F,
    ) -> Option<Vec<crate::cards::pokemon::TypeModifier>>
    where
        F: Into<Option<Vec<crate::cards::pokemon::TypeModifier>>>,
    {
        let resistances: Option<Vec<crate::cards::pokemon::TypeModifier>> = resistances.into();
        std::mem::replace(&mut self.resistances, resistances)
    }

    /// Sets the field: `resistances`. Returns the struct itself.
    #[must_use]
    pub fn with_resistances<F>(mut self, resistances: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::pokemon::TypeModifier>>>,
    {
        self.set_resistances(resistances);
        self
    }
}
