// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A paging response.
/// struct PageResponse {
///    
///     // The page number.
///     page: u32;
///    
///     // The page size.
///     page_size: u32;
///    
///     // The total number of items.
///     total: u32;
/// }
/// ```
#[derive(
    Copy,
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct PageResponse {
    page: u32,
    page_size: u32,
    total: u32,
}

impl PageResponse {
    //! Construction

    /// Creates a new [PageResponse].
    pub const fn new(page: u32, page_size: u32, total: u32) -> Self {
        Self {
            page,
            page_size,
            total,
        }
    }

    /// Creates a new [PageResponse].
    pub fn from<F1, F2, F3>(page: F1, page_size: F2, total: F3) -> Self
    where
        F1: Into<u32>,
        F2: Into<u32>,
        F3: Into<u32>,
    {
        Self::new(page.into(), page_size.into(), total.into())
    }
}

impl PageResponse {
    //! Field: `page`

    /// Gets the field: `page`.
    #[must_use]
    pub fn page(&self) -> u32 {
        self.page
    }

    /// Sets the field: `page`. Returns the previous value.
    pub fn set_page(&mut self, page: u32) -> u32 {
        std::mem::replace(&mut self.page, page)
    }

    /// Sets the field: `page`. Returns the struct itself.
    #[must_use]
    pub fn with_page(mut self, page: u32) -> Self {
        self.set_page(page);
        self
    }
}

impl PageResponse {
    //! Field: `page_size`

    /// Gets the field: `page_size`.
    #[must_use]
    pub fn page_size(&self) -> u32 {
        self.page_size
    }

    /// Sets the field: `page_size`. Returns the previous value.
    pub fn set_page_size(&mut self, page_size: u32) -> u32 {
        std::mem::replace(&mut self.page_size, page_size)
    }

    /// Sets the field: `page_size`. Returns the struct itself.
    #[must_use]
    pub fn with_page_size(mut self, page_size: u32) -> Self {
        self.set_page_size(page_size);
        self
    }
}

impl PageResponse {
    //! Field: `total`

    /// Gets the field: `total`.
    #[must_use]
    pub fn total(&self) -> u32 {
        self.total
    }

    /// Sets the field: `total`. Returns the previous value.
    pub fn set_total(&mut self, total: u32) -> u32 {
        std::mem::replace(&mut self.total, total)
    }

    /// Sets the field: `total`. Returns the struct itself.
    #[must_use]
    pub fn with_total(mut self, total: u32) -> Self {
        self.set_total(total);
        self
    }
}
