// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_cards` request.
/// message GetCardsRequest {
///    
///     // The query.
///     query: api.v0.cards.CardQuery = 1;
///    
///     // The paging request.
///     paging: core.api.PageRequest = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetCardsRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    query: Option<crate::api::v0::cards::CardQuery>,
    #[serde(skip_serializing_if = "Option::is_none")]
    paging: Option<crate::core::api::PageRequest>,
}

impl GetCardsRequest {
    //! Field: `query`

    /// Gets the field: `query`.
    #[must_use]
    pub fn query(&self) -> Option<&crate::api::v0::cards::CardQuery> {
        self.query.as_ref()
    }

    /// Sets the field: `query`. Returns the previous value.
    pub fn set_query<F>(&mut self, query: F) -> Option<crate::api::v0::cards::CardQuery>
    where
        F: Into<Option<crate::api::v0::cards::CardQuery>>,
    {
        let query: Option<crate::api::v0::cards::CardQuery> = query.into();
        std::mem::replace(&mut self.query, query)
    }

    /// Sets the field: `query`. Returns the struct itself.
    #[must_use]
    pub fn with_query<F>(mut self, query: F) -> Self
    where
        F: Into<Option<crate::api::v0::cards::CardQuery>>,
    {
        self.set_query(query);
        self
    }
}

impl GetCardsRequest {
    //! Field: `paging`

    /// Gets the field: `paging`.
    #[must_use]
    pub fn paging(&self) -> Option<crate::core::api::PageRequest> {
        self.paging
    }

    /// Sets the field: `paging`. Returns the previous value.
    pub fn set_paging<F>(&mut self, paging: F) -> Option<crate::core::api::PageRequest>
    where
        F: Into<Option<crate::core::api::PageRequest>>,
    {
        let paging: Option<crate::core::api::PageRequest> = paging.into();
        std::mem::replace(&mut self.paging, paging)
    }

    /// Sets the field: `paging`. Returns the struct itself.
    #[must_use]
    pub fn with_paging<F>(mut self, paging: F) -> Self
    where
        F: Into<Option<crate::core::api::PageRequest>>,
    {
        self.set_paging(paging);
        self
    }
}
