// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A Pokémon energy type.
#[derive(
    Copy,
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub enum EnergyType {
    Grass,

    Fire,

    Water,

    Lightning,

    Psychic,

    Fighting,

    Darkness,

    Metal,

    Fairy,

    Dragon,

    Colorless,
}
