// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A pokemon.
/// struct Pokemon {
///    
///     // The dex number. (ex: 3)
///     dex: u32;
///    
///     // The name. (ex: Mega Venusaur)
///     name: core.web.Name;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Pokemon {
    dex: u32,
    name: crate::core::web::Name,
}

impl Pokemon {
    //! Construction

    /// Creates a new [Pokemon].
    pub const fn new(dex: u32, name: crate::core::web::Name) -> Self {
        Self { dex, name }
    }

    /// Creates a new [Pokemon].
    pub fn from<F1, F2>(dex: F1, name: F2) -> Self
    where
        F1: Into<u32>,
        F2: Into<crate::core::web::Name>,
    {
        Self::new(dex.into(), name.into())
    }
}

impl Pokemon {
    //! Field: `dex`

    /// Gets the field: `dex`.
    #[must_use]
    pub fn dex(&self) -> u32 {
        self.dex
    }

    /// Sets the field: `dex`. Returns the previous value.
    pub fn set_dex(&mut self, dex: u32) -> u32 {
        std::mem::replace(&mut self.dex, dex)
    }

    /// Sets the field: `dex`. Returns the struct itself.
    #[must_use]
    pub fn with_dex(mut self, dex: u32) -> Self {
        self.set_dex(dex);
        self
    }
}

impl Pokemon {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> &crate::core::web::Name {
        &self.name
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name(&mut self, name: crate::core::web::Name) -> crate::core::web::Name {
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name(mut self, name: crate::core::web::Name) -> Self {
        self.set_name(name);
        self
    }
}
