// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // Card metadata. (artists, level, rarity, release date & flavor)
/// message CardMeta {
///    
///     // The illustrators.
///     artists: []core.web.Name = 1;
///    
///     // The level. (ex: `42`)
///     level: core.web.Name = 2;
///    
///     // The rarity. (ex: `Rare Holo`)
///     rarity: core.web.Name = 3;
///    
///     // The release date.
///     release_date: date = 4;
///    
///     // The flavor text.
///     flavor: string = 5;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct CardMeta {
    #[serde(skip_serializing_if = "Option::is_none")]
    artists: Option<Vec<crate::core::web::Name>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    level: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    rarity: Option<crate::core::web::Name>,
    #[serde(skip_serializing_if = "Option::is_none")]
    release_date: Option<proto_packet::types::Date>,
    #[serde(skip_serializing_if = "Option::is_none")]
    flavor: Option<String>,
}

impl CardMeta {
    //! Field: `artists`

    /// Gets the field: `artists`.
    #[must_use]
    pub fn artists(&self) -> Option<&Vec<crate::core::web::Name>> {
        self.artists.as_ref()
    }

    /// Sets the field: `artists`. Returns the previous value.
    pub fn set_artists<F>(&mut self, artists: F) -> Option<Vec<crate::core::web::Name>>
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        let artists: Option<Vec<crate::core::web::Name>> = artists.into();
        std::mem::replace(&mut self.artists, artists)
    }

    /// Sets the field: `artists`. Returns the struct itself.
    #[must_use]
    pub fn with_artists<F>(mut self, artists: F) -> Self
    where
        F: Into<Option<Vec<crate::core::web::Name>>>,
    {
        self.set_artists(artists);
        self
    }
}

impl CardMeta {
    //! Field: `level`

    /// Gets the field: `level`.
    #[must_use]
    pub fn level(&self) -> Option<&crate::core::web::Name> {
        self.level.as_ref()
    }

    /// Sets the field: `level`. Returns the previous value.
    pub fn set_level<F>(&mut self, level: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let level: Option<crate::core::web::Name> = level.into();
        std::mem::replace(&mut self.level, level)
    }

    /// Sets the field: `level`. Returns the struct itself.
    #[must_use]
    pub fn with_level<F>(mut self, level: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_level(level);
        self
    }
}

impl CardMeta {
    //! Field: `rarity`

    /// Gets the field: `rarity`.
    #[must_use]
    pub fn rarity(&self) -> Option<&crate::core::web::Name> {
        self.rarity.as_ref()
    }

    /// Sets the field: `rarity`. Returns the previous value.
    pub fn set_rarity<F>(&mut self, rarity: F) -> Option<crate::core::web::Name>
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        let rarity: Option<crate::core::web::Name> = rarity.into();
        std::mem::replace(&mut self.rarity, rarity)
    }

    /// Sets the field: `rarity`. Returns the struct itself.
    #[must_use]
    pub fn with_rarity<F>(mut self, rarity: F) -> Self
    where
        F: Into<Option<crate::core::web::Name>>,
    {
        self.set_rarity(rarity);
        self
    }
}

impl CardMeta {
    //! Field: `release_date`

    /// Gets the field: `release_date`.
    #[must_use]
    pub fn release_date(&self) -> Option<proto_packet::types::Date> {
        self.release_date
    }

    /// Sets the field: `release_date`. Returns the previous value.
    pub fn set_release_date<F>(&mut self, release_date: F) -> Option<proto_packet::types::Date>
    where
        F: Into<Option<proto_packet::types::Date>>,
    {
        let release_date: Option<proto_packet::types::Date> = release_date.into();
        std::mem::replace(&mut self.release_date, release_date)
    }

    /// Sets the field: `release_date`. Returns the struct itself.
    #[must_use]
    pub fn with_release_date<F>(mut self, release_date: F) -> Self
    where
        F: Into<Option<proto_packet::types::Date>>,
    {
        self.set_release_date(release_date);
        self
    }
}

impl CardMeta {
    //! Field: `flavor`

    /// Gets the field: `flavor`.
    #[must_use]
    pub fn flavor(&self) -> Option<&str> {
        self.flavor.as_deref()
    }

    /// Sets the field: `flavor`. Returns the previous value.
    pub fn set_flavor<F>(&mut self, flavor: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let flavor: Option<String> = flavor.into();
        std::mem::replace(&mut self.flavor, flavor)
    }

    /// Sets the field: `flavor`. Returns the struct itself.
    #[must_use]
    pub fn with_flavor<F>(mut self, flavor: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_flavor(flavor);
        self
    }
}
