// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // Attack damage. (ex: `30`, `30+`, `30×`, `?`)
/// message Damage {
///    
///     // The base damage. (absent for variable `?` damage)
///     scalar: u32 = 1;
///    
///     // The modifier. (ex: `+` in `30+`)
///     modifier: cards.meta.DamageModifier = 2;
///    
///     // Whether the damage is variable. (ex: `?`)
///     variable: bool = 3;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct Damage {
    #[serde(skip_serializing_if = "Option::is_none")]
    scalar: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    modifier: Option<crate::cards::meta::DamageModifier>,
    #[serde(skip_serializing_if = "Option::is_none")]
    variable: Option<bool>,
}

impl Damage {
    //! Field: `scalar`

    /// Gets the field: `scalar`.
    #[must_use]
    pub fn scalar(&self) -> Option<u32> {
        self.scalar
    }

    /// Sets the field: `scalar`. Returns the previous value.
    pub fn set_scalar<F>(&mut self, scalar: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let scalar: Option<u32> = scalar.into();
        std::mem::replace(&mut self.scalar, scalar)
    }

    /// Sets the field: `scalar`. Returns the struct itself.
    #[must_use]
    pub fn with_scalar<F>(mut self, scalar: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_scalar(scalar);
        self
    }
}

impl Damage {
    //! Field: `modifier`

    /// Gets the field: `modifier`.
    #[must_use]
    pub fn modifier(&self) -> Option<crate::cards::meta::DamageModifier> {
        self.modifier
    }

    /// Sets the field: `modifier`. Returns the previous value.
    pub fn set_modifier<F>(&mut self, modifier: F) -> Option<crate::cards::meta::DamageModifier>
    where
        F: Into<Option<crate::cards::meta::DamageModifier>>,
    {
        let modifier: Option<crate::cards::meta::DamageModifier> = modifier.into();
        std::mem::replace(&mut self.modifier, modifier)
    }

    /// Sets the field: `modifier`. Returns the struct itself.
    #[must_use]
    pub fn with_modifier<F>(mut self, modifier: F) -> Self
    where
        F: Into<Option<crate::cards::meta::DamageModifier>>,
    {
        self.set_modifier(modifier);
        self
    }
}

impl Damage {
    //! Field: `variable`

    /// Gets the field: `variable`.
    #[must_use]
    pub fn variable(&self) -> Option<bool> {
        self.variable
    }

    /// Sets the field: `variable`. Returns the previous value.
    pub fn set_variable<F>(&mut self, variable: F) -> Option<bool>
    where
        F: Into<Option<bool>>,
    {
        let variable: Option<bool> = variable.into();
        std::mem::replace(&mut self.variable, variable)
    }

    /// Sets the field: `variable`. Returns the struct itself.
    #[must_use]
    pub fn with_variable<F>(mut self, variable: F) -> Self
    where
        F: Into<Option<bool>>,
    {
        self.set_variable(variable);
        self
    }
}
