// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A `get_cards` response.
/// message GetCardsResponse {
///    
///     // The cards.
///     cards: []cards.card.Card = 1;
///    
///     // The paging response.
///     paging: core.api.PageResponse = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GetCardsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    cards: Option<Vec<crate::cards::card::Card>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    paging: Option<crate::core::api::PageResponse>,
}

impl GetCardsResponse {
    //! Field: `cards`

    /// Gets the field: `cards`.
    #[must_use]
    pub fn cards(&self) -> Option<&Vec<crate::cards::card::Card>> {
        self.cards.as_ref()
    }

    /// Sets the field: `cards`. Returns the previous value.
    pub fn set_cards<F>(&mut self, cards: F) -> Option<Vec<crate::cards::card::Card>>
    where
        F: Into<Option<Vec<crate::cards::card::Card>>>,
    {
        let cards: Option<Vec<crate::cards::card::Card>> = cards.into();
        std::mem::replace(&mut self.cards, cards)
    }

    /// Sets the field: `cards`. Returns the struct itself.
    #[must_use]
    pub fn with_cards<F>(mut self, cards: F) -> Self
    where
        F: Into<Option<Vec<crate::cards::card::Card>>>,
    {
        self.set_cards(cards);
        self
    }
}

impl GetCardsResponse {
    //! Field: `paging`

    /// Gets the field: `paging`.
    #[must_use]
    pub fn paging(&self) -> Option<crate::core::api::PageResponse> {
        self.paging
    }

    /// Sets the field: `paging`. Returns the previous value.
    pub fn set_paging<F>(&mut self, paging: F) -> Option<crate::core::api::PageResponse>
    where
        F: Into<Option<crate::core::api::PageResponse>>,
    {
        let paging: Option<crate::core::api::PageResponse> = paging.into();
        std::mem::replace(&mut self.paging, paging)
    }

    /// Sets the field: `paging`. Returns the struct itself.
    #[must_use]
    pub fn with_paging<F>(mut self, paging: F) -> Self
    where
        F: Into<Option<crate::core::api::PageResponse>>,
    {
        self.set_paging(paging);
        self
    }
}
