// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// The card service.
pub trait CardService: Send + Sync {
    /// Gets the sets.
    fn get_sets(
        &self,
        request: crate::api::v0::cards::GetSetsRequest,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            crate::api::v0::cards::GetSetsResponse,
            ::proto_packet::service::ServiceError,
        >,
    > + Send
    + '_;
}

pub fn router<S>(service: ::std::sync::Arc<S>) -> ::proto_packet::axum::Router
where
    S: CardService + 'static,
{
    ::proto_packet::axum::Router::new().route(
        "/api.v0.cards.CardService/get_sets",
        ::proto_packet::axum::routing::post({
            let service = service.clone();
            move |::proto_packet::axum::Json(request): ::proto_packet::axum::Json<
                crate::api::v0::cards::GetSetsRequest,
            >| {
                let service = service.clone();
                async move {
                    service
                        .get_sets(request)
                        .await
                        .map(::proto_packet::axum::Json)
                }
            }
        }),
    )
}
